[theme]
primaryColor = "#4B7BEC"
backgroundColor = "#F7FAFC"
secondaryBackgroundColor = "#EDF2F7"
textColor = "#1A202C"
font = "sans serif"

[server]
maxUploadSize = 50
enableXsrfProtection = true
enableCORS = false 